stages:
  - test
  - build-and-push

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

test:
  stage: test
  script:
    - chmod +x ./mvnw
    - ./mvnw test -Dnexus.url=$NEXUS_URL -s ci-settings.xml
  only:
    - develop

build-and-push:
  stage: build-and-push
  script:
    - chmod +x ./mvnw
    - ./mvnw package -DskipTests -Dnexus.url=$NEXUS_URL -s ci-settings.xml
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  only:
    - develop
