stages:
  - test
  - build
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

test:
  stage: test
  script:
    - chmod +x ./mvnw
    - ./mvnw test -Dnexus.url=$NEXUS_URL -s ci-settings.xml
  only:
    - develop

build:
  stage: build
  script:
    - chmod +x ./mvnw
    - ./mvnw package -DskipTests -Dnexus.url=$NEXUS_URL -s ci-settings.xml
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
  only:
    - develop

docker:
  stage: docker
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  only:
    - develop
