apiVersion: v1
kind: ConfigMap
metadata:
  name: task-api-config
  namespace: devops-l3gl
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/taskdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SERVER_PORT: "8085"
  SERVER_SERVLET_CONTEXT_PATH: /l3gl

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
  namespace: devops-l3gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: dieuvitek/task-api:latest
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: task-api-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: 200m
              memory: 250Mi
            limits:
              cpu: 400m
              memory: 500Mi
          readinessProbe:
            httpGet:
              path: /l3gl/actuator/health/readiness
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /l3gl/actuator/health/liveness
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: task-api-service
  namespace: devops-l3gl
spec:
  type: ClusterIP
  selector:
    app: task-api
  ports:
    - port: 8085
      targetPort: 8085

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-api-ingress
  namespace: devops-l3gl
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /l3gl
            pathType: Prefix
            backend:
              service:
                name: task-api-service
                port:
                  number: 8085